In [3]:
import pandas as pd
import kamping
import numpy as np
from kamping.data.dataset import MetaboliteProteinInteraction

%load_ext autoreload
%autoreload 2

In [62]:
mpi = pd.read_csv('../data/string_stitch/raw/9606.protein_chemical.links.v5.0.tsv', sep='\t')

# filter mpi with chemical not start with CIDs
mpi = mpi[~mpi['chemical'].str.startswith('CIDs')]

unique_compounds = mpi['chemical'].unique()
unique_compounds

array(['CIDm91758680', 'CIDm91758408', 'CIDm91758407', ...,
       'CIDm00000004', 'CIDm00000003', 'CIDm00000001'], dtype=object)

In [49]:
# remove compound start with CIDs
unique_compounds = [compound for compound in unique_compounds if not compound.startswith('CIDs')]
unique_compounds

['CIDm91758680',
 'CIDm91758408',
 'CIDm91758407',
 'CIDm91758406',
 'CIDm91758404',
 'CIDm91758403',
 'CIDm91758402',
 'CIDm91758401',
 'CIDm91758389',
 'CIDm91758271',
 'CIDm91757967',
 'CIDm91757966',
 'CIDm91757965',
 'CIDm91757964',
 'CIDm91757962',
 'CIDm91757960',
 'CIDm91757948',
 'CIDm91757947',
 'CIDm91757946',
 'CIDm91757945',
 'CIDm91757944',
 'CIDm91757941',
 'CIDm91757938',
 'CIDm91757937',
 'CIDm91757705',
 'CIDm91754990',
 'CIDm91754987',
 'CIDm91754984',
 'CIDm91754983',
 'CIDm91754982',
 'CIDm91754981',
 'CIDm91754979',
 'CIDm91754977',
 'CIDm91754976',
 'CIDm91754975',
 'CIDm91754974',
 'CIDm91754972',
 'CIDm91754971',
 'CIDm91754969',
 'CIDm91754964',
 'CIDm91754961',
 'CIDm91754958',
 'CIDm91754956',
 'CIDm91754955',
 'CIDm91754953',
 'CIDm91754952',
 'CIDm91754951',
 'CIDm91754946',
 'CIDm91754711',
 'CIDm91754604',
 'CIDm91754603',
 'CIDm91754602',
 'CIDm91754600',
 'CIDm91754581',
 'CIDm91754554',
 'CIDm91754243',
 'CIDm91754234',
 'CIDm91754232',
 'CIDm91754231',
 'CIDm91754228',
 'CIDm91754227',
 'CIDm91753580',
 'CIDm91753435',
 'CIDm91753270',
 'CIDm91751258',
 'CIDm91751196',
 'CIDm91751184',
 'CIDm91751164',
 'CIDm91750293',
 'CIDm91750195',
 'CIDm91750039',
 'CIDm91748033',
 'CIDm91747900',
 'CIDm91747166',
 'CIDm91746572',
 'CIDm91746550',
 'CIDm91746481',
 'CIDm91746378',
 'CIDm91746331',
 'CIDm91746319',
 'CIDm91746317',
 'CIDm91746315',
 'CIDm91746314',
 'CIDm91746313',
 'CIDm91746312',
 'CIDm91746311',
 'CIDm91746295',
 'CIDm91746294',
 'CIDm91739162',
 'CIDm91727408',
 'CIDm91716943',
 'CIDm91710915',
 'CIDm91699622',
 'CIDm91692905',
 'CIDm91668558',
 'CIDm91668557',
 'CIDm91668556',
 'CIDm91668555',
 'CIDm91668554',
 'CIDm91668553',
 'CIDm91668551',
 'CIDm91668550',
 'CIDm91668545',
 'CIDm91668544',
 'CIDm91668543',
 'CIDm91668540',
 'CIDm91668539',
 'CIDm91668532',
 'CIDm91668531',
 'CIDm91668528',
 'CIDm91668184',
 'CIDm91667932',
 'CIDm91667928',
 'CIDm91667926',
 'CIDm91667715',
 'CIDm91667430',
 'CIDm91667429',
 'CIDm91667428',
 'CIDm91667421',
 'CIDm91667420',
 'CIDm91667415',
 'CIDm91667414',
 'CIDm91667413',
 'CIDm91667412',
 'CIDm91667411',
 'CIDm91667409',
 'CIDm91667408',
 'CIDm91667406',
 'CIDm91667405',
 'CIDm91667404',
 'CIDm91667403',
 'CIDm91666471',
 'CIDm91666469',
 'CIDm91666468',
 'CIDm91666467',
 'CIDm91666466',
 'CIDm91666463',
 'CIDm91666459',
 'CIDm91666458',
 'CIDm91666457',
 'CIDm91666456',
 'CIDm91666445',
 'CIDm91666347',
 'CIDm91666345',
 'CIDm91666322',
 'CIDm91666319',
 'CIDm91666313',
 'CIDm91665256',
 'CIDm91664024',
 'CIDm91664020',
 'CIDm91664017',
 'CIDm91664013',
 'CIDm91664012',
 'CIDm91664007',
 'CIDm91664002',
 'CIDm91663465',
 'CIDm91663464',
 'CIDm91663444',
 'CIDm91663443',
 'CIDm91663437',
 'CIDm91663271',
 'CIDm91663255',
 'CIDm91663192',
 'CIDm91663129',
 'CIDm91632909',
 'CIDm91623344',
 'CIDm91623334',
 'CIDm91623329',
 'CIDm91623327',
 'CIDm91623326',
 'CIDm91623324',
 'CIDm91623323',
 'CIDm91623020',
 'CIDm91620187',
 'CIDm91617971',
 'CIDm91617630',
 'CIDm91616559',
 'CIDm91616435',
 'CIDm91616422',
 'CIDm91616358',
 'CIDm91615522',
 'CIDm91614560',
 'CIDm91614073',
 'CIDm91613579',
 'CIDm91613561',
 'CIDm91612801',
 'CIDm91612599',
 'CIDm91612275',
 'CIDm91611974',
 'CIDm91610865',
 'CIDm91610072',
 'CIDm91609726',
 'CIDm91609326',
 'CIDm91609320',
 'CIDm91609169',
 'CIDm91609041',
 'CIDm91608615',
 'CIDm91608456',
 'CIDm91608251',
 'CIDm91607816',
 'CIDm91607805',
 'CIDm91607520',
 'CIDm91606547',
 'CIDm91606271',
 'CIDm91605851',
 'CIDm91605615',
 'CIDm91605236',
 'CIDm91604364',
 'CIDm91604360',
 'CIDm91604268',
 'CIDm91603822',
 'CIDm91603774',
 'CIDm91603583',
 'CIDm91603096',
 'CIDm91602940',
 'CIDm91602719',
 'CIDm91602368',
 'CIDm91602281',
 'CIDm91602122',
 'CIDm91601132',
 'CIDm91600427',
 'CIDm91599644',
 'CIDm91598531',
 'CIDm91598375',
 'CIDm91597903',
 'CIDm91597553',
 'CIDm91596862',
 'CIDm91596607',
 'CIDm91596579',
 'CIDm91596373',
 'CIDm91596222',
 'CIDm91596152',
 'CIDm91595832',
 'CIDm91595650',
 'CIDm91595371',
 'CIDm91594590',
 'CIDm91594409',
 'CIDm91594181',
 'CIDm91593217',
 'CIDm91592988',
 'CIDm91592865',
 'CIDm91592643',
 'CIDm91592640',
 'CIDm91592353',
 'CIDm91591100',
 'CIDm91589696',
 'CIDm91589650',
 'CIDm91589147',
 'CIDm91588933',
 'CIDm91588676',
 'CIDm91588540',
 'CIDm91588518',
 'CIDm91588270',
 'CIDm91587773',
 'CIDm91587673',
 'CIDm91587001',
 'CIDm91586643',
 'CIDm91586532',
 'CIDm91586143',
 'CIDm91585947',
 'CIDm91585844',
 'CIDm91585581',
 'CIDm91585382',
 'CIDm91583236',
 'CIDm91582920',
 'CIDm91582556',
 'CIDm91582319',
 'CIDm91582103',
 'CIDm91581925',
 'CIDm91581757',
 'CIDm91581619',
 'CIDm91581576',
 'CIDm91581403',
 'CIDm91581049',
 'CIDm91580835',
 'CIDm91580413',
 'CIDm91580072',
 'CIDm91580014',
 'CIDm91579984',
 'CIDm91579755',
 'CIDm91579718',
 'CIDm91579387',
 'CIDm91578871',
 'CIDm91578553',
 'CIDm91578497',
 'CIDm91578232',
 'CIDm91578026',
 'CIDm91577872',
 'CIDm91576850',
 'CIDm91576786',
 'CIDm91576752',
 'CIDm91576267',
 'CIDm91575812',
 'CIDm91575358',
 'CIDm91575167',
 'CIDm91572850',
 'CIDm91572826',
 'CIDm91572792',
 'CIDm91572766',
 'CIDm91572503',
 'CIDm91572189',
 'CIDm91572003',
 'CIDm91571673',
 'CIDm91571110',
 'CIDm91570959',
 'CIDm91570801',
 'CIDm91568524',
 'CIDm91568397',
 'CIDm91567888',
 'CIDm91567681',
 'CIDm91566775',
 'CIDm91566163',
 'CIDm91566040',
 'CIDm91565702',
 'CIDm91565661',
 'CIDm91565548',
 'CIDm91565190',
 'CIDm91564615',
 'CIDm91564342',
 'CIDm91563695',
 'CIDm91563516',
 'CIDm91562519',
 'CIDm91562471',
 'CIDm91562173',
 'CIDm91561988',
 'CIDm91561272',
 'CIDm91561164',
 'CIDm91561119',
 'CIDm91560765',
 'CIDm91560703',
 'CIDm91560371',
 'CIDm91560275',
 'CIDm91559802',
 'CIDm91559221',
 'CIDm91559185',
 'CIDm91559053',
 'CIDm91558355',
 'CIDm91558175',
 'CIDm91558094',
 'CIDm91557792',
 'CIDm91557725',
 'CIDm91557562',
 'CIDm91557397',
 'CIDm91557393',
 'CIDm91556837',
 'CIDm91556723',
 'CIDm91556677',
 'CIDm91556301',
 'CIDm91556022',
 'CIDm91555114',
 'CIDm91554845',
 'CIDm91554105',
 'CIDm91553977',
 'CIDm91553671',
 'CIDm91553005',
 'CIDm91552785',
 'CIDm91552645',
 'CIDm91552113',
 'CIDm91551968',
 'CIDm91551665',
 'CIDm91551634',
 'CIDm91551404',
 'CIDm91551321',
 'CIDm91550693',
 'CIDm91550656',
 'CIDm91550630',
 'CIDm91550477',
 'CIDm91549682',
 'CIDm91549538',
 'CIDm91549198',
 'CIDm91549012',
 'CIDm91548902',
 'CIDm91548865',
 'CIDm91548640',
 'CIDm91548190',
 'CIDm91548119',
 'CIDm91547624',
 'CIDm91547208',
 'CIDm91546957',
 'CIDm91546365',
 'CIDm91546278',
 'CIDm91546243',
 'CIDm91546195',
 'CIDm91545903',
 'CIDm91545760',
 'CIDm91545453',
 'CIDm91545424',
 'CIDm91543882',
 'CIDm91543879',
 'CIDm91543852',
 'CIDm91543479',
 'CIDm91543425',
 'CIDm91542910',
 'CIDm91542736',
 'CIDm91542196',
 'CIDm91541688',
 'CIDm91541553',
 'CIDm91541128',
 'CIDm91540989',
 'CIDm91540763',
 'CIDm91540663',
 'CIDm91539826',
 'CIDm91539726',
 'CIDm91539604',
 'CIDm91539491',
 'CIDm91539057',
 'CIDm91538979',
 'CIDm91538595',
 'CIDm91538007',
 'CIDm91537858',
 'CIDm91537666',
 'CIDm91537620',
 'CIDm91537189',
 'CIDm91537173',
 'CIDm91536653',
 'CIDm91536371',
 'CIDm91536054',
 'CIDm91535892',
 'CIDm91535751',
 'CIDm91534145',
 'CIDm91533997',
 'CIDm91533417',
 'CIDm91533376',
 'CIDm91533174',
 'CIDm91533053',
 'CIDm91532727',
 'CIDm91532504',
 'CIDm91532343',
 'CIDm91531952',
 'CIDm91531854',
 'CIDm91531638',
 'CIDm91530875',
 'CIDm91530807',
 'CIDm91530653',
 'CIDm91530583',
 'CIDm91529959',
 'CIDm91529599',
 'CIDm91528963',
 'CIDm91528884',
 'CIDm91527971',
 'CIDm91527760',
 'CIDm91527505',
 'CIDm91527112',
 'CIDm91526997',
 'CIDm91526533',
 'CIDm91525985',
 'CIDm91525717',
 'CIDm91525367',
 'CIDm91525206',
 'CIDm91524838',
 'CIDm91524830',
 'CIDm91524705',
 'CIDm91524164',
 'CIDm91523960',
 'CIDm91523942',
 'CIDm91523929',
 'CIDm91523879',
 'CIDm91523183',
 'CIDm91523058',
 'CIDm91522931',
 'CIDm91522735',
 'CIDm91522624',
 'CIDm91522529',
 'CIDm91522240',
 'CIDm91522179',
 'CIDm91522041',
 'CIDm91521715',
 'CIDm91520575',
 'CIDm91520320',
 'CIDm91520130',
 'CIDm91520059',
 'CIDm91519229',
 'CIDm91519085',
 'CIDm91518690',
 'CIDm91518562',
 'CIDm91518110',
 'CIDm91518033',
 'CIDm91517393',
 'CIDm91517273',
 'CIDm91517248',
 'CIDm91517100',
 'CIDm91517014',
 'CIDm91516895',
 'CIDm91516266',
 'CIDm91515526',
 'CIDm91514907',
 'CIDm91514722',
 'CIDm91514156',
 'CIDm91514136',
 'CIDm91514122',
 'CIDm91513739',
 'CIDm91513501',
 'CIDm91513375',
 'CIDm91513059',
 'CIDm91512911',
 'CIDm91511753',
 'CIDm91511462',
 'CIDm91511058',
 'CIDm91511051',
 'CIDm91510252',
 'CIDm91509475',
 'CIDm91509425',
 'CIDm91509022',
 'CIDm91508248',
 'CIDm91508149',
 'CIDm91508074',
 'CIDm91507838',
 'CIDm91507514',
 'CIDm91507500',
 'CIDm91507354',
 'CIDm91507112',
 'CIDm91506706',
 'CIDm91506547',
 'CIDm91506528',
 'CIDm91506487',
 'CIDm91506354',
 'CIDm91505787',
 'CIDm91505578',
 'CIDm91505060',
 'CIDm91504220',
 'CIDm91504116',
 'CIDm91503612',
 'CIDm91503594',
 'CIDm91502775',
 'CIDm91502371',
 'CIDm91502298',
 'CIDm91502192',
 'CIDm91501804',
 'CIDm91501611',
 'CIDm91501409',
 'CIDm91501029',
 'CIDm91500839',
 'CIDm91500714',
 'CIDm91500604',
 'CIDm91500422',
 'CIDm91500022',
 'CIDm91499341',
 'CIDm91499207',
 'CIDm91498588',
 'CIDm91498282',
 'CIDm91497882',
 'CIDm91497746',
 'CIDm91497635',
 'CIDm91497256',
 'CIDm91496079',
 'CIDm91495937',
 'CIDm91495868',
 'CIDm91495834',
 'CIDm91495813',
 'CIDm91495805',
 'CIDm91495604',
 'CIDm91495259',
 'CIDm91494671',
 'CIDm91494614',
 'CIDm91494585',
 'CIDm91494249',
 'CIDm91493172',
 'CIDm91491268',
 'CIDm91491077',
 'CIDm91490873',
 'CIDm91490772',
 'CIDm91490771',
 'CIDm91490522',
 'CIDm91490213',
 'CIDm91489878',
 'CIDm91488976',
 'CIDm91488726',
 'CIDm91488573',
 'CIDm91488457',
 'CIDm91488304',
 'CIDm91487954',
 'CIDm91487035',
 'CIDm91486848',
 'CIDm91486805',
 'CIDm91486551',
 'CIDm91486348',
 'CIDm91486075',
 'CIDm91485925',
 'CIDm91485915',
 'CIDm91485821',
 'CIDm91485541',
 'CIDm91485501',
 'CIDm91484955',
 'CIDm91484913',
 'CIDm91484844',
 'CIDm91484825',
 'CIDm91484095',
 'CIDm91483618',
 'CIDm91483421',
 'CIDm91483407',
 'CIDm91483200',
 'CIDm91483116',
 'CIDm91482804',
 'CIDm91482486',
 'CIDm91482466',
 'CIDm91481151',
 'CIDm91479827',
 'CIDm91478304',
 'CIDm91477851',
 'CIDm91477690',
 'CIDm91477214',
 'CIDm91476841',
 'CIDm91476761',
 'CIDm91476759',
 'CIDm91476205',
 'CIDm91475685',
 'CIDm91475430',
 'CIDm91475298',
 'CIDm91475272',
 'CIDm91474810',
 'CIDm91473870',
 'CIDm91473745',
 'CIDm91473728',
 'CIDm91472928',
 'CIDm91472039',
 'CIDm91471923',
 'CIDm91471895',
 'CIDm91471628',
 'CIDm91471129',
 'CIDm91470950',
 'CIDm91470484',
 'CIDm91470313',
 'CIDm91470236',
 'CIDm91470225',
 'CIDm91469525',
 'CIDm91469234',
 'CIDm91469185',
 'CIDm91468798',
 'CIDm91468702',
 'CIDm91468090',
 'CIDm91467054',
 'CIDm91466979',
 'CIDm91465787',
 'CIDm91465751',
 'CIDm91465659',
 'CIDm91465529',
 'CIDm91465521',
 'CIDm91465417',
 'CIDm91465110',
 'CIDm91464572',
 'CIDm91464216',
 'CIDm91463710',
 'CIDm91463384',
 'CIDm91462883',
 'CIDm91462582',
 'CIDm91461206',
 'CIDm91460229',
 'CIDm91460195',
 'CIDm91459902',
 'CIDm91459472',
 'CIDm91459316',
 'CIDm91459299',
 'CIDm91459295',
 'CIDm91459204',
 'CIDm91458752',
 'CIDm91458427',
 'CIDm91458150',
 'CIDm91457927',
 'CIDm91457349',
 'CIDm91457184',
 'CIDm91457090',
 'CIDm91456897',
 'CIDm91456467',
 'CIDm91456213',
 'CIDm91456085',
 'CIDm91455946',
 'CIDm91455355',
 'CIDm91454534',
 'CIDm91454486',
 'CIDm91454290',
 'CIDm91453959',
 'CIDm91453941',
 'CIDm91453081',
 'CIDm91452994',
 'CIDm91451691',
 'CIDm91451514',
 'CIDm91451088',
 'CIDm91450891',
 'CIDm91450180',
 'CIDm91449760',
 'CIDm91449541',
 'CIDm91449512',
 'CIDm91449487',
 'CIDm91449271',
 'CIDm91449152',
 'CIDm91448549',
 'CIDm91447998',
 'CIDm91447595',
 'CIDm91447332',
 'CIDm91445749',
 'CIDm91445493',
 'CIDm91445473',
 'CIDm91445441',
 'CIDm91445230',
 'CIDm91444489',
 'CIDm91444198',
 'CIDm91444163',
 'CIDm91443878',
 'CIDm91443694',
 'CIDm91442949',
 'CIDm91442430',
 'CIDm91442061',
 'CIDm91441102',
 'CIDm91441086',
 'CIDm91439860',
 'CIDm91439837',
 'CIDm91439784',
 'CIDm91439512',
 'CIDm91438993',
 'CIDm91438482',
 'CIDm91438456',
 'CIDm91437264',
 'CIDm91436330',
 'CIDm91435651',
 'CIDm91435298',
 'CIDm91435274',
 'CIDm91434140',
 'CIDm91433912',
 'CIDm91433210',
 'CIDm91432999',
 'CIDm91432962',
 'CIDm91432874',
 'CIDm91432706',
 'CIDm91432622',
 'CIDm91432524',
 'CIDm91431867',
 'CIDm91431704',
 'CIDm91431650',
 'CIDm91431421',
 'CIDm91431162',
 'CIDm91431105',
 'CIDm91429957',
 'CIDm91429919',
 'CIDm91429452',
 'CIDm91429280',
 'CIDm91429257',
 'CIDm91429172',
 'CIDm91428738',
 'CIDm91428083',
 'CIDm91427718',
 'CIDm91427602',
 'CIDm91427495',
 'CIDm91427426',
 'CIDm91427309',
 'CIDm91427045',
 'CIDm91426341',
 'CIDm91426327',
 'CIDm91426324',
 'CIDm91425439',
 'CIDm91425335',
 'CIDm91425207',
 'CIDm91423882',
 'CIDm91423414',
 'CIDm91422953',
 'CIDm91422819',
 'CIDm91422435',
 'CIDm91422075',
 'CIDm91421981',
 'CIDm91421956',
 'CIDm91421830',
 'CIDm91421124',
 'CIDm91421066',
 'CIDm91420925',
 'CIDm91420908',
 'CIDm91420862',
 'CIDm91420495',
 'CIDm91419688',
 'CIDm91419437',
 'CIDm91419079',
 'CIDm91419054',
 'CIDm91418560',
 'CIDm91418533',
 'CIDm91417735',
 'CIDm91417541',
 'CIDm91417259',
 'CIDm91417015',
 'CIDm91416960',
 'CIDm91416797',
 'CIDm91416599',
 'CIDm91416506',
 'CIDm91416203',
 'CIDm91415990',
 'CIDm91415781',
 'CIDm91415209',
 'CIDm91414952',
 'CIDm91414496',
 'CIDm91414202',
 'CIDm91413616',
 'CIDm91413247',
 'CIDm91413064',
 'CIDm91413051',
 'CIDm91412761',
 'CIDm91412691',
 'CIDm91412640',
 'CIDm91411759',
 'CIDm91411737',
 'CIDm91411637',
 'CIDm91411010',
 'CIDm91411000',
 'CIDm91410655',
 'CIDm91410210',
 'CIDm91409400',
 'CIDm91409115',
 'CIDm91408784',
 'CIDm91408504',
 'CIDm91407761',
 'CIDm91407300',
 'CIDm91407213',
 'CIDm91406786',
 'CIDm91406620',
 'CIDm91406245',
 'CIDm91405561',
 'CIDm91405247',
 'CIDm91405065',
 'CIDm91403932',
 'CIDm91403340',
 'CIDm91403084',
 'CIDm91402977',
 'CIDm91402479',
 'CIDm91401656',
 'CIDm91401390',
 'CIDm91401255',
 'CIDm91401182',
 'CIDm91400030',
 'CIDm91399467',
 'CIDm91399224',
 'CIDm91398982',
 'CIDm91398086',
 'CIDm91397886',
 'CIDm91397865',
 'CIDm91397484',
 'CIDm91397477',
 'CIDm91396883',
 'CIDm91396194',
 'CIDm91395167',
 'CIDm91395059',
 'CIDm91394605',
 'CIDm91394265',
 'CIDm91394142',
 'CIDm91393554',
 'CIDm91393387',
 'CIDm91392180',
 'CIDm91392034',
 'CIDm91391102',
 'CIDm91390779',
 'CIDm91390490',
 'CIDm91390467',
 'CIDm91390324',
 'CIDm91389784',
 'CIDm91389423',
 'CIDm91389252',
 'CIDm91388919',
 'CIDm91388442',
 'CIDm91388300',
 'CIDm91387937',
 'CIDm91387568',
 'CIDm91387442',
 'CIDm91387126',
 'CIDm91387121',
 'CIDm91386865',
 'CIDm91386857',
 'CIDm91385650',
 'CIDm91385254',
 'CIDm91384651',
 'CIDm91384166',
 'CIDm91384003',
 'CIDm91383853',
 'CIDm91383739',
 'CIDm91382982',
 'CIDm91382941',
 'CIDm91382761',
 'CIDm91382721',
 'CIDm91382621',
 'CIDm91382562',
 'CIDm91382205',
 'CIDm91381029',
 'CIDm91381002',
 'CIDm91380987',
 'CIDm91380864',
 'CIDm91380723',
 'CIDm91380677',
 'CIDm91380208',
 'CIDm91379860',
 'CIDm91379802',
 'CIDm91379718',
 'CIDm91379595',
 'CIDm91378950',
 'CIDm91378773',
 'CIDm91377940',
 'CIDm91377564',
 'CIDm91377353',
 'CIDm91377318',
 'CIDm91376530',
 'CIDm91376410',
 'CIDm91375997',
 'CIDm91375968',
 'CIDm91375798',
 'CIDm91375411',
 'CIDm91375021',
 'CIDm91374954',
 'CIDm91374405',
 'CIDm91374316',
 'CIDm91374292',
 'CIDm91374054',
 'CIDm91373633',
 'CIDm91373283',
 'CIDm91373043',
 'CIDm91372839',
 'CIDm91372308',
 'CIDm91372170',
 'CIDm91372063',
 'CIDm91371395',
 'CIDm91371116',
 'CIDm91371016',
 'CIDm91370668',
 'CIDm91370354',
 'CIDm91369736',
 'CIDm91369708',
 'CIDm91369703',
 'CIDm91369685',
 'CIDm91369226',
 'CIDm91369129',
 'CIDm91368954',
 'CIDm91368911',
 'CIDm91368573',
 'CIDm91368190',
 'CIDm91368184',
 'CIDm91367996',
 'CIDm91367915',
 'CIDm91367657',
 'CIDm91367610',
 'CIDm91367159',
 'CIDm91365436',
 'CIDm91365368',
 'CIDm91364747',
 'CIDm91364409',
 'CIDm91363923',
 'CIDm91363693',
 'CIDm91363562',
 'CIDm91363531',
 'CIDm91363345',
 'CIDm91362959',
 'CIDm91362714',
 'CIDm91361466',
 'CIDm91360979',
 'CIDm91360894',
 'CIDm91360740',
 'CIDm91360539',
 'CIDm91359807',
 'CIDm91359108',
 'CIDm91359015',
 'CIDm91358877',
 'CIDm91358823',
 'CIDm91358668',
 'CIDm91358393',
 'CIDm91357576',
 'CIDm91357245',
 'CIDm91357237',
 'CIDm91356701',
 'CIDm91356572',
 'CIDm91356165',
 'CIDm91356097',
 'CIDm91355368',
 'CIDm91354795',
 'CIDm91354194',
 'CIDm91353997',
 'CIDm91353843',
 'CIDm91353581',
 'CIDm91353578',
 'CIDm91352509',
 'CIDm91351991',
 'CIDm91351882',
 'CIDm91351316',
 'CIDm91351230',
 'CIDm91351204',
 'CIDm91350935',
 'CIDm91350040',
 'CIDm91349817',
 'CIDm91348291',
 'CIDm91348287',
 'CIDm91346901',
 'CIDm91346294',
 'CIDm91346242',
 'CIDm91346019',
 'CIDm91345647',
 'CIDm91345551',
 'CIDm91345199',
 'CIDm91345190',
 'CIDm91344785',
 'CIDm91344652',
 'CIDm91344255',
 'CIDm91344096',
 'CIDm91344095',
 'CIDm91343644',
 'CIDm91343264',
 'CIDm91343124',
 'CIDm91342520',
 'CIDm91341697',
 'CIDm91341643',
 'CIDm91341290',
 ...]

In [69]:
import pandas as pd

# Initialize an empty DataFrame to store the filtered data
filtered_smiles = pd.DataFrame()

# Define the chunk size
chunk_size = 1000000  # Adjust based on your memory capacity

# Read the first TSV file in chunks
for chunk in pd.read_csv('../data/string_stitch/raw/chemicals.v5.0.tsv', sep='\t', chunksize=chunk_size):
    # Filter the chunk based on unique_compounds
    filtered_chunk = chunk[chunk['chemical'].isin(unique_compounds)]
    # Append the filtered chunk to the filtered_smiles DataFrame
    filtered_smiles = pd.concat([filtered_smiles, filtered_chunk], ignore_index=True)

# Now filtered_smiles contains the filtered data

In [70]:
# # Save the filtered data to a new TSV file
filtered_smiles.to_csv('../data/string_stitch/raw/filtered_output.tsv', sep='\t', index=False)

In [71]:
# import the smile strings
smiles = pd.read_csv('../data/string_stitch/raw/filtered_output.tsv', sep='\t', usecols=['chemical', 'SMILES_string'], index_col='chemical')
smiles

                                                 SMILES_string
chemical
CIDm00000001                  CC(=O)OC(CC(=O)[O-])C[N+](C)(C)C
CIDm00000003                          C1=CC(C(C(=C1)C(=O)O)O)O
CIDm00000004                                           CC(CN)O
CIDm00000005                              C(C(=O)COP(=O)(O)O)N
CIDm00000006         C1=CC(=C(C=C1[N+](=O)[O-])[N+](=O)[O-])Cl
...                                                        ...
CIDm91758404                  C1CCC(CC1)COC2=CC=CC(=C2)C(CCO)O
CIDm91758406          C1COCCC1NC2=NC=C3CCN(CC3=N2)S(=O)(=O)CCS
CIDm91758407       CNC(=O)C1=CC=CC=C1NC2=CC(=NC=C2Cl)NC3CCOCC3
CIDm91758408   C1COCCC1NC2=NC=C(C(=N2)NC3=CC=CC=C3NC(=O)CCS)Cl
CIDm91758680  C(C(=O)[O-])C(CC(=O)[O-])(C(=O)[O-])O.N.O.[Fe+3]

[374278 rows x 1 columns]

In [72]:
from rdkit import Chem

mols = []

for compound in unique_compounds:
    # check if the compound exists in the smiles DataFrame
    if compound in smiles.index:
        # convert the SMILES string to a RDKit molecule object
        mols.append(Chem.MolFromSmiles(smiles.loc[compound, 'SMILES_string']))
    else:
        # if the compound does not exist, append None
        print(f'{compound} not found')
        mols.append(None)
    # create a pd.DataFrame
ROMols = pd.DataFrame({'id': list(unique_compounds), 'ROMol': mols})
# remove the None values
ROMols = ROMols.dropna()

CIDm73330332 not found
CIDm70678717 not found
CIDm44237211 not found
CIDm44237133 not found
CIDm25098796 not found
CIDm05189703 not found
CIDm03080603 not found
CIDm00002828 not found

In [75]:
compound_embeddings = kamping.get_mol_embeddings_from_dataframe(ROMols, transformer='morgan', dtype=np.int8)

WARNING:root:Successfully parse 374254 rows with valid SMILES from the MOL file!
'
                    total 0 Invalid rows with "None" in the ROMol column
WARNING:root: [], removed from the final output!

In [76]:
# save the embeddings using h5py
import h5py
with h5py.File('../data/string_stitch/raw/compound_embeddings.h5', 'w') as f:
    for key, value in compound_embeddings.items():
        f.create_dataset(key, data=value)

In [77]:
compound_embeddings

{'CIDm91758680': array([0, 0, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91758408': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758407': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91758406': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758404': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91758403': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758402': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758401': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758389': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758271': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757967': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757966': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757965': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91757964': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757962': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757960': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757948': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757947': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757946': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757945': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757944': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757941': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757938': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757937': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757705': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754990': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754987': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754984': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754983': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754982': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754981': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754979': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754977': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754976': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754975': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754974': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754972': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754971': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754969': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754964': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754961': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754958': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754956': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754955': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754953': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754952': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754951': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754946': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754711': array([0, 0, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91754604': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754603': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754602': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754600': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754581': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754554': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754243': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754234': array([1, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754232': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754231': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754228': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754227': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91753580': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91753435': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91753270': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751258': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751196': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751184': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751164': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750293': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750195': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750039': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91748033': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91747900': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91747166': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746572': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746550': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746481': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746378': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746331': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746317': array([0, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91746315': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746314': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746313': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746312': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746311': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91746295': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746294': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91739162': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91727408': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91716943': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91710915': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91699622': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91692905': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668558': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668557': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668556': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668555': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668554': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668551': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668550': array([1, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91668545': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668544': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668543': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668540': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668539': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668532': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668531': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668528': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668184': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91667932': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667928': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667926': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667715': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667430': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667429': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667428': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667421': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667420': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667415': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667414': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667413': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667412': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667411': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667409': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667408': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667406': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667405': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667404': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667403': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666471': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666469': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666468': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666467': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666466': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666463': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666459': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666458': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666457': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666456': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666445': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666347': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666345': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666322': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666313': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91665256': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664024': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664020': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664017': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91664013': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664012': array([0, 1, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91664007': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664002': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663465': array([1, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663464': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663444': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663443': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663437': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663271': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663255': array([1, 0, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91663192': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663129': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91632909': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623344': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623334': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91623329': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623327': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623326': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623324': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623323': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623020': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91620187': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91617971': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91617630': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91616559': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616435': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616422': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616358': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91615522': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91614560': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91614073': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91613579': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91613561': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612801': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612599': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612275': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91611974': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91610865': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91610072': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609726': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609326': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609320': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609169': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609041': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608456': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608251': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607816': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607805': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607520': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91606547': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91606271': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605851': array([1, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605236': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91604364': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91604360': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91604268': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603822': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603774': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603583': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603096': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602940': array([0, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91602719': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602368': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91602281': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602122': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91601132': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91600427': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91599644': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91598531': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91598375': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91597903': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91597553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596862': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596607': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596579': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596373': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596222': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596152': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91595832': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91595650': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91595371': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594590': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594409': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594181': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91593217': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592988': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592865': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592643': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592640': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592353': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91591100': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589696': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589650': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589147': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91588933': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588676': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588540': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588518': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588270': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587773': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587673': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587001': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586643': array([1, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586532': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586143': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585947': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585844': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585581': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585382': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91583236': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582920': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582556': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582103': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581925': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581757': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581619': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581576': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581403': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581049': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91580835': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580413': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580072': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580014': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579984': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579755': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579718': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579387': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578871': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578497': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578232': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578026': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91577872': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576850': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576786': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576752': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576267': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575812': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575358': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575167': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572850': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572826': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572792': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91572766': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572503': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572189': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572003': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91571673': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91571110': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91570959': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91570801': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91568524': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91568397': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91567888': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91567681': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566775': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566163': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566040': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565702': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565661': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565548': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565190': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91564615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91564342': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91563695': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91563516': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562519': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562471': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562173': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561988': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561272': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561164': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),

In [15]:
# load the dictionary of embeddings from the h5 file
with h5py.File("../data/string_stitch/raw/compound_embeddings.h5", "r") as f:
    # Initialize an empty dictionary
    compound_embeddings = {}

    # Iterate over the items in the file
    for key in f.keys():
        # Read each dataset into the dictionary
        compound_embeddings[key] = f[key][...]

In [94]:
compound_embeddings

{'CIDm91758680': array([0, 0, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91758408': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758407': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91758406': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758404': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91758403': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758402': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758401': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758389': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91758271': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757967': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757966': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757965': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91757964': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757962': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757960': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757948': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757947': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757946': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757945': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757944': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757941': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757938': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757937': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91757705': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754990': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754987': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754984': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754983': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754982': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754981': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754979': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754977': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754976': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754975': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754974': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754972': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91754971': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754969': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754964': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754961': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754958': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754956': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754955': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754953': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754952': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754951': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754946': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754711': array([0, 0, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91754604': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754603': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754602': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754600': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754581': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754554': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754243': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754234': array([1, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754232': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754231': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754228': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91754227': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91753580': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91753435': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91753270': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751258': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751196': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751184': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91751164': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750293': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750195': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91750039': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91748033': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91747900': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91747166': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746572': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746550': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746481': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746378': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746331': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746317': array([0, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91746315': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746314': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746313': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746312': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746311': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91746295': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91746294': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91739162': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91727408': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91716943': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91710915': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91699622': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91692905': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668558': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668557': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668556': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668555': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668554': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668551': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668550': array([1, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91668545': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668544': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668543': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668540': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668539': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668532': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668531': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668528': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91668184': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91667932': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667928': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667926': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667715': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667430': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667429': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667428': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667421': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667420': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667415': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667414': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667413': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667412': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667411': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667409': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667408': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667406': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667405': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667404': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91667403': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666471': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666469': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666468': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666467': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666466': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666463': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666459': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666458': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666457': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666456': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666445': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666347': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666345': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666322': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91666313': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91665256': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664024': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664020': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664017': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91664013': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664012': array([0, 1, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91664007': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91664002': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663465': array([1, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663464': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663444': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663443': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663437': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663271': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663255': array([1, 0, 0, ..., 0, 0, 1], dtype=int8),
 'CIDm91663192': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91663129': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91632909': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623344': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623334': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91623329': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623327': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623326': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623324': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623323': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91623020': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91620187': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91617971': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91617630': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91616559': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616435': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616422': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91616358': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91615522': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91614560': array([0, 1, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91614073': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91613579': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91613561': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612801': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612599': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91612275': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91611974': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91610865': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91610072': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609726': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609326': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609320': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609169': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91609041': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608456': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91608251': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607816': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607805': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91607520': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91606547': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91606271': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605851': array([1, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91605236': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91604364': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91604360': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91604268': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603822': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603774': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603583': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91603096': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602940': array([0, 1, 0, ..., 1, 0, 0], dtype=int8),
 'CIDm91602719': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602368': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91602281': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91602122': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91601132': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91600427': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91599644': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91598531': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91598375': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91597903': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91597553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596862': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596607': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596579': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596373': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596222': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91596152': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91595832': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91595650': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91595371': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594590': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594409': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91594181': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91593217': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592988': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592865': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592643': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592640': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91592353': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91591100': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589696': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589650': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91589147': array([0, 1, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91588933': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588676': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588540': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588518': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91588270': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587773': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587673': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91587001': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586643': array([1, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586532': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91586143': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585947': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585844': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585581': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91585382': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91583236': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582920': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582556': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582319': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91582103': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581925': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581757': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581619': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581576': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581403': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91581049': array([0, 0, 1, ..., 0, 0, 0], dtype=int8),
 'CIDm91580835': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580413': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580072': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91580014': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579984': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579755': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579718': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91579387': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578871': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578553': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578497': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578232': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91578026': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91577872': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576850': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576786': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576752': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91576267': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575812': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575358': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91575167': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572850': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572826': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572792': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91572766': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572503': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572189': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91572003': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91571673': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91571110': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91570959': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91570801': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91568524': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91568397': array([0, 0, 0, ..., 0, 1, 0], dtype=int8),
 'CIDm91567888': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91567681': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566775': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566163': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91566040': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565702': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565661': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565548': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91565190': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91564615': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91564342': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91563695': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91563516': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562519': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562471': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91562173': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561988': array([0, 0, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561272': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),
 'CIDm91561164': array([0, 1, 0, ..., 0, 0, 0], dtype=int8),

In [79]:
import numpy as np
from sklearn.decomposition import PCA

# Extract the embeddings and keys
keys = list(compound_embeddings.keys())
embeddings = np.array(list(compound_embeddings.values()))

# Apply PCA to reduce to 128 dimensions
pca = PCA(n_components=128)
reduced_embeddings = pca.fit_transform(embeddings)

# Create a new dictionary with the reduced embeddings
reduced_mol_embeddings = {keys[i]: reduced_embeddings[i] for i in range(len(keys))}

# Print the reduced embeddings dictionary
# print(reduced_mol_embeddings)

In [80]:
# convert reduced_mol_embeddings to float32
for key, value in reduced_mol_embeddings.items():
    reduced_mol_embeddings[key] = value.astype(np.float32)

# save to h5 file
with h5py.File('../data/string_stitch/raw/compound_embeddings_PCA.h5', 'w') as f:
    for key, value in reduced_mol_embeddings.items():
        f.create_dataset(key, data=value)

# Convert string to Uniprot ID

In [82]:
uniprot_df = pd.read_table('/Users/cgu3/Documents/Grape-Pi/data/miscellaneous/uniprotkb_proteome_UP000005640_AND_revi_2023_10_05.tsv', sep='\t')
uniprot_df = uniprot_df[['STRING', 'Entry']]
uniprot_df.dropna(subset=['STRING'], inplace=True)
uniprot_df['STRING'] = uniprot_df['STRING'].str.replace(';', '')
uniprot_df

                     STRING       Entry
2      9606.ENSP00000482829  A0A0B4J2F2
7      9606.ENSP00000377112      A0AV02
8      9606.ENSP00000371212      A0AV96
9      9606.ENSP00000419279      A0AVF1
10     9606.ENSP00000372394      A0AVI4
...                     ...         ...
20371  9606.ENSP00000429608      Q96PS1
20373  9606.ENSP00000402355      Q96T59
20383  9606.ENSP00000359558      Q9H1L0
20388  9606.ENSP00000455079      Q9H693
20394  9606.ENSP00000418086      Q9HBI5

[18528 rows x 2 columns]

In [83]:
mpi['protein'] = kamping.utils.mapping(mpi['protein'], uniprot_df, na_rm=False)
# drop the rows with missing values
mpi.dropna(subset=['protein'], inplace=True)

In [84]:
mpi.to_csv('../data/string_stitch/raw/9606.protein_chemical_translated.links.v5.0.tsv', sep='\t', index=False)

In [4]:
# load ../data/string_stitch/raw/9606.protein_chemical_translated.links.v5.0.ts
mpi = pd.read_csv('../data/string_stitch/raw/9606.protein_chemical_translated.links.v5.0.tsv', sep='\t')
mpi

             chemical protein  combined_score
0        CIDm91758680  Q9BZR9             154
1        CIDm91758408  Q6NTF9             225
2        CIDm91758408  Q12774             178
3        CIDm91758408  Q9Y3P4             225
4        CIDm91758408  O95140             162
...               ...     ...             ...
5949655  CIDm00000001  Q00059             150
5949656  CIDm00000001  Q9NTX5             279
5949657  CIDm00000001  P40925             311
5949658  CIDm00000001  O14727             322
5949659  CIDm00000001  Q01415             197

[5949660 rows x 3 columns]

In [11]:
mpi[mpi['combined_score'] > 900].to_csv('../data/string_stitch/raw/9606.protein_chemical_translated.filtered.links.v5.0.tsv', sep='\t', index=False)

# Process metabolite-metabolite interaction data

In [88]:
mmi = pd.read_csv('../data/string_stitch/raw/chemical_chemical.links.detailed.v5.0.tsv', sep='\t')
mmi

,chemical1,chemical2,similarity,experimental,database,textmining,combined_score
0,CIDm00024759,CIDs00024759,0,0,900,0,900
1,CIDs91758695,CIDs00107694,0,0,0,230,230
2,CIDs91758695,CIDs11013287,0,0,0,230,230
3,CIDs91758695,CIDs11980957,0,0,0,328,328
4,CIDs91758695,CIDs00013078,0,0,0,162,162
...,...,...,...,...,...,...,...
17705813,CIDm00000001,CIDm87081431,753,0,0,173,173
17705814,CIDm00000001,CIDm90857042,0,0,0,218,218
17705815,CIDm00000001,CIDm91056687,0,0,0,294,294
17705816,CIDm00000001,CIDm91213096,0,0,0,357,357
17705817,CIDs00024759,CIDm00024759,0,0,900,0,900

In [89]:
# filter row with chemical1 start with CIDs or chemical2 start with CIDs
mmi = mmi[~mmi['chemical1'].str.startswith('CIDs')]
mmi = mmi[~mmi['chemical2'].str.startswith('CIDs')]
mmi

,chemical1,chemical2,similarity,experimental,database,textmining,combined_score
9665846,CIDm91758680,CIDm00000066,0,0,0,230,230
9665847,CIDm91758680,CIDm00000124,750,0,0,274,274
9665848,CIDm91758680,CIDm00000136,0,0,0,170,170
9665849,CIDm91758680,CIDm00001145,0,0,0,179,179
9665850,CIDm91758680,CIDm00006914,0,0,0,215,215
...,...,...,...,...,...,...,...
17705812,CIDm00000001,CIDm87076413,500,0,0,176,176
17705813,CIDm00000001,CIDm87081431,753,0,0,173,173
17705814,CIDm00000001,CIDm90857042,0,0,0,218,218
17705815,CIDm00000001,CIDm91056687,0,0,0,294,294
17705816,CIDm00000001,CIDm91213096,0,0,0,357,357

# Use dataset to create a graph from the data

In [15]:
data = MetaboliteProteinInteraction(root='../data/string_stitch')

Processing...
/Users/cgu3/Documents/experiments/KAMPING/kamping/data/dataset.py:67: UserWarning: Creating a tensor from a list of numpy.ndarrays is extremely slow. Please consider converting the list to a single numpy.ndarray with numpy.array() before converting to a tensor. (Triggered internally at /Users/runner/work/pytorch/pytorch/pytorch/torch/csrc/utils/tensor_new.cpp:281.)
  data['gene'].x = torch.tensor([protein_embeddings[node] for node in proteins if node in protein_embeddings], dtype=torch.float)
Done!
/Users/cgu3/Documents/experiments/KAMPING/kamping/data/dataset.py:12: FutureWarning: You are using `torch.load` with `weights_only=False` (the current default value), which uses the default pickle module implicitly. It is possible to construct malicious pickle data which will execute arbitrary code during unpickling (See https://github.com/pytorch/pytorch/blob/main/SECURITY.md#untrusted-models for more details). In a future release, the default value for `weights_only` will be flipped to `True`. This limits the functions that could be executed during unpickling. Arbitrary objects will no longer be allowed to be loaded via this mode unless they are explicitly allowlisted by the user via `torch.serialization.add_safe_globals`. We recommend you start setting `weights_only=True` for any use case where you don't have full control of the loaded file. Please open an issue on GitHub for any issues related to this experimental feature.
  self.data, self.slices = torch.load(self.processed_paths[0])

In [97]:
data[0]

HeteroData(
  gene={ x=[16752, 1024] },
  compound={ x=[343286, 128] },
  (gene, to, gene)={ edge_index=[2, 10605120] },
  (compound, to, gene)={ edge_index=[2, 5596399] }
)

In [100]:
import pickle

# save the data as pickle file
with open('../data/pyg_graph_with_string_stitch_900_metabolite', 'wb') as f:
    pickle.dump(data[0], f)